services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'swaggerDB'
      MYSQL_USER: 'yu7i'
      MYSQL_PASSWORD: '53cret'
      MYSQL_ROOT_PASSWORD: '53cret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
